[[config]]
name = "Odoo LS"
odoo_path = "${workspaceFolder}/src/community"
addons_paths = [
    "${workspaceFolder}/src/community/addons",
    "${workspaceFolder}/src/community/odoo/addons",
    "${workspaceFolder}/src/enterprise",
    "${workspaceFolder}/src/extra-addons/design-themes",
    "${workspaceFolder}/src/extra-addons/iap-apps",
    "${workspaceFolder}/src/extra-addons/industry",
    "${workspaceFolder}/src/extra-addons/personal",
    "${workspaceFolder}/src/extra-addons/runbot",
    "${workspaceFolder}/src/extra-addons/tutorials"
]
python_path = "python3"
